version: '3.4'

services:
  jenkins:
    build: .
    ports:
      - "8080:8080"
      - "50000:50000"
    container_name: jenkins-local
    volumes:
      - $PWD/jenkins:/var/jenkins_home

